export type DigestWindowKind = "noon" | "evening";

export type VisitorIdentityMode = "cookie" | "ip_fallback";
export type DeviceType = "desktop" | "mobile" | "tablet" | "bot" | "unknown";
export type BotStatus = "verified_bot" | "probable_bot" | "possible_bot" | "not_bot" | "unknown";
export type LeadLevel = "BOT" | "LOW" | "MEDIUM" | "HIGH" | "HOT";
export type HumanStatus = "engaged_human" | "probable_human" | "low_engagement" | "probable_bot" | "unknown";

export type DigestEventInput = {
  eventId: string;
  eventType: string;
  path: string;
  pageTitle: string | null;
  referrer: string | null;
  utmSource: string | null;
  utmMedium: string | null;
  utmCampaign: string | null;
  utmTerm: string | null;
  utmContent: string | null;
  durationSeconds: number | null;
  rawIp: string | null;
  ipHash: string | null;
  visitorId?: string;
  sessionId?: string;
  identityMode?: VisitorIdentityMode;
  automationHint?: boolean;
  userAgent?: string | null;
  browser?: string | null;
  os?: string | null;
  deviceType?: DeviceType;
  countryCode?: string | null;
  region?: string | null;
  city?: string | null;
  asn?: string | null;
  asnOrg?: string | null;
  isDatacenter?: boolean | null;
  cloudProvider?: string | null;
  botStatus?: BotStatus;
  botReasons?: string[];
  occurredAt: string;
  digestWindow: string;
  expiresAt: string;
  sessionKey?: string;
};

export type DigestScoreReason = { code: string; points: number; label: string };

export type VisitorDigestRecord = {
  id: string;
  rawIp: string | null;
  ipHash: string | null;
  visitorId: string;
  sessionId: string;
  identityMode: VisitorIdentityMode;
  sessionKey?: string;
  userAgent: string | null;
  browser: string | null;
  os: string | null;
  deviceType: DeviceType;
  countryCode: string | null;
  region: string | null;
  city: string | null;
  asn: string | null;
  asnOrg: string | null;
  isDatacenter: boolean | null;
  cloudProvider: string | null;
  botStatus: BotStatus;
  botReasons: string[];
  engagementSeconds: number;
  uniquePageCount: number;
  validRepeatVisit: boolean;
  leadLevel: LeadLevel;
  humanStatus: HumanStatus;
  firstSeenAt: string;
  lastSeenAt: string;
  totalEvents: number;
  totalVisits: number;
  totalSessionSeconds: number;
  visitedPages: string[];
  productPages: string[];
  eventSummary: Record<string, number>;
  sessionEngagementSeconds: number;
  sessionUniquePageCount: number;
  sessionVisitedPages: string[];
  sessionEventSummary: Record<string, number>;
  referrer: string | null;
  utmSource: string | null;
  utmMedium: string | null;
  utmCampaign: string | null;
  utmTerm: string | null;
  utmContent: string | null;
  behaviorScore: number;
  scoreReasons: DigestScoreReason[];
  digestWindow: string;
  sentAt: string | null;
  expiresAt: string;
};
