"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Detail = { inquiry: Record<string, unknown>; linkedInquiry: Record<string, unknown> | null; events: Array<Record<string, unknown>>; notificationStatus: string | null };
const value = (record: Record<string, unknown>, key: string) => String(record[key] ?? "暂未识别");

export default function AdminInquiryDetailClient({ id }: { id: string }) {
  const [detail, setDetail] = useState<Detail | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { fetch(`/api/admin/inquiries/${encodeURIComponent(id)}`, { cache: "no-store" }).then(async (response) => { if (!response.ok) throw new Error(response.status === 401 ? "UNAUTHORIZED" : "NOT_FOUND"); setDetail(await response.json() as Detail); }).catch((reason: Error) => setError(reason.message)); }, [id]);
  if (error === "UNAUTHORIZED") return <main style={{ maxWidth: 720, margin: "4rem auto", padding: "1.5rem" }}><h1>Inquiry administration</h1><p>Please sign in before opening this inquiry.</p><Link href="/admin/login">Open admin login</Link></main>;
  if (error) return <main style={{ padding: "2rem" }}><p role="alert">Inquiry unavailable.</p><Link href="/admin/inquiries">Back to inquiries</Link></main>;
  if (!detail) return <main style={{ padding: "2rem" }}><p>Loading inquiry...</p></main>;
  const inquiry = detail.inquiry;
  const visitor = inquiry.inquiryType === "company_visitor_lead";
  return <main style={{ maxWidth: 960, margin: "0 auto", padding: "2rem" }}><p><Link href="/admin/inquiries">Back to inquiries</Link></p><h1>{visitor ? "企业访客识别" : "客户主动询盘"}</h1>{visitor ? <p style={{ border: "1px solid #c98b24", padding: "1rem" }}>该记录来自企业级 IP 识别和网站访问行为，并非客户主动填写的询盘，不能确定具体访问人员身份，请在联系或进一步处理前进行人工核实。</p> : null}<section><h2>Record</h2><dl>{[["Type", visitor ? "企业访客识别" : "客户主动询盘"],["Source", value(inquiry,"sourceLabel")],["Status", value(inquiry,"status")],["Company", value(inquiry,"companyName")],["Domain", value(inquiry,"companyDomain")],["Country", value(inquiry,"countryName")],["Industry", value(inquiry,"industry")],["Employees", value(inquiry,"employeeRange")],["Network", value(inquiry,"networkType")],["Confidence", visitor ? `${Math.round(Number(inquiry.providerConfidence ?? 0) * 100)}%` : "暂未识别"],["Lead score", visitor ? value(inquiry,"leadScore") : "暂未识别"],["Notification", detail.notificationStatus ?? "暂无记录"]].map(([label, content]) => <div key={label}><dt style={{ fontWeight: 700 }}>{label}</dt><dd>{content}</dd></div>)}</dl></section>{visitor ? <><section><h2>Contact details</h2><p>Name: 暂未识别<br />Email: 暂未识别<br />Phone: 暂未识别<br />Message: 暂未识别</p></section><section><h2>Score reasons</h2><ul>{(Array.isArray(inquiry.scoreReasons) ? inquiry.scoreReasons : []).map((reason) => <li key={String((reason as Record<string, unknown>).code)}>{value(reason as Record<string, unknown>,"label")} +{value(reason as Record<string, unknown>,"points")}</li>)}</ul></section><section><h2>Visitor timeline</h2><p>First seen: {value(inquiry,"firstSeenAt")}<br />Last seen: {value(inquiry,"lastSeenAt")}<br />Total visits: {value(inquiry,"totalVisits")}<br />Total events: {value(inquiry,"totalEvents")}<br />Latest referrer: {value(inquiry,"latestReferrer")}<br />Latest UTM source: {value(inquiry,"latestUtmSource")}</p><ol>{detail.events.map((event) => <li key={String(event.eventId)}>{value(event,"occurredAt")} — {value(event,"eventType")} — {value(event,"path")} — {value(event,"referrer")} — {value(event,"utmSource")}</li>)}</ol></section></> : <section><h2>Customer inquiry</h2><p>Name: {value(inquiry,"customerName")}<br />Email: {value(inquiry,"customerEmail")}<br />Phone: {value(inquiry,"customerPhone")}<br />Company: {value(inquiry,"companyName")}<br />Message: {value(inquiry,"customerMessage")}</p></section>}{detail.linkedInquiry ? <section><h2>Linked inquiry</h2><p><Link href={`/admin/inquiries/${String(detail.linkedInquiry.id)}`}>{value(detail.linkedInquiry,"inquiryType")} — {value(detail.linkedInquiry,"id")}</Link></p></section> : null}</main>;
}
