import { ArrowRight, Check, ClipboardCheck, Factory, FileCheck2, Ruler, Scissors, Settings2, ShieldCheck } from "lucide-react";
import Header from "@/components/site/Header";
import SiteFooter from "@/components/site/SiteFooter";
import { Link } from "@/i18n/navigation";
import { capabilities, complianceDocuments, processSteps } from "@/data/siteContent";

const icons = [Ruler, FileCheck2, Settings2, Factory, Scissors, ShieldCheck, ClipboardCheck];

export default function CapabilitiesPage({ locale }: { locale: string }) {
  const isZh = locale === "zh";
  return <div className="texture-paper min-h-screen text-(--kh-ink)"><Header /><main>
    <section className="mx-auto max-w-7xl px-4 pb-12 pt-14 sm:px-6 lg:px-8 lg:pb-20 lg:pt-20"><p className="kh-eyebrow">Kehong · Manufacturing capabilities</p><h1 className="kh-editorial-heading mt-4 max-w-4xl text-5xl sm:text-7xl">{isZh ? "把包装需求拆成可确认的制造步骤" : "Capabilities that turn a packaging brief into a production path."}</h1><p className="kh-lede mt-6">{isZh ? "从结构、文件和打样，到印刷、后加工、质检和出口协作，按项目需求确认每个环节。" : "From structure, artwork and sampling through printing, finishing, quality checks and export coordination, each capability is reviewed around the project brief."}</p><Link href="/contact" className="kh-button kh-button-primary mt-7">Get a custom quote <ArrowRight className="size-4" /></Link></section>
    <section className="border-y border-(--kh-line) bg-white/60"><div className="mx-auto grid max-w-7xl gap-4 px-4 py-12 sm:px-6 md:grid-cols-2 lg:grid-cols-3 lg:px-8">{capabilities.map((item, index) => { const Icon = icons[index] ?? Settings2; return <article key={item.slug} className="rounded-lg border border-(--kh-line) bg-(--kh-surface) p-5"><div className="flex items-center gap-3 text-(--kh-brass)"><span className="grid size-10 place-items-center rounded-full bg-(--kh-paper-deep)"><Icon className="size-5" /></span><h2 className="text-xl font-semibold text-(--kh-ink)">{item.title}</h2></div><p className="mt-4 text-sm leading-6 text-(--kh-muted)">{item.summary}</p><p className="mt-3 border-l-2 border-(--kh-brass-soft) pl-3 text-sm font-semibold leading-6 text-(--kh-ink)">{item.buyerValue}</p><p className="mt-4 text-xs leading-5 text-(--kh-muted)"><strong>Bring:</strong> {item.input}</p></article>; })}</div></section>
    <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><div className="grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><p className="kh-eyebrow">Custom packaging process</p><h2 className="kh-editorial-heading mt-3 text-4xl">{isZh ? "从询盘到出货，每一步都可追踪" : "A clear path from inquiry to export handoff."}</h2></div><ol className="grid gap-3 sm:grid-cols-2">{processSteps.map((step) => <li key={step.number} className="rounded-lg border border-(--kh-line) bg-(--kh-surface) p-5"><p className="text-xs font-semibold tracking-[.18em] text-(--kh-brass)">{step.number}</p><h3 className="mt-2 font-semibold">{step.title}</h3><p className="mt-2 text-sm leading-6 text-(--kh-muted)">{step.body}</p></li>)}</ol></div></section>
    <section className="texture-ink border-y border-(--kh-line)"><div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><div className="flex items-center gap-3"><ShieldCheck className="size-6 text-(--kh-brass-soft)" /><h2 className="text-2xl font-semibold">Quality Control & Third-Party Testing</h2></div><p className="mt-3 max-w-2xl text-sm leading-6 text-white/75">Compliance documents are available upon request. Test scope, issuing body and date are confirmed against relevant project records before sharing.</p><div className="mt-6 grid gap-3 sm:grid-cols-3">{["Incoming material inspection", "Artwork and dimension check", "Final packing inspection"].map((item) => <p key={item} className="flex gap-2 rounded-md border border-white/15 bg-white/8 px-4 py-3 text-sm font-medium"><Check className="size-4 shrink-0 text-(--kh-brass-soft)" />{item}</p>)}</div><p className="mt-4 text-xs text-white/70">{complianceDocuments.length} compliance document pathway configured; no unverified certificate is displayed publicly.</p></div></section>
    <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><div className="rounded-[10px] border border-(--kh-line) bg-(--kh-brass-soft) p-7 sm:p-9"><h2 className="kh-editorial-heading text-3xl">Ready to review a structure?</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-(--kh-ink)">Send dimensions, drawings, material preferences and destination details. Kehong will confirm the next practical step.</p><Link href="/contact" className="kh-button kh-button-primary mt-5">Start a packaging project <ArrowRight className="size-4" /></Link></div></section>
  </main><SiteFooter /></div>;
}
