import Image from "next/image";
import { ArrowRight, Check, Layers3, ShieldCheck } from "lucide-react";
import { Link } from "@/i18n/navigation";
import { packagingCategories } from "@/data/packagingCategories";
import { industryGroups } from "@/data/industries";
import { showcaseImages } from "@/data/visuals";
import { companyProfile } from "@/data/company";

const productionLines = [
  { number: "01", title: "Paper materials & converting", body: "Material selection, slitting and converting are coordinated around the approved specification.", image: showcaseImages.portalSwatch, href: "/products" },
  { number: "02", title: "Food & bakery structures", body: "Paper boxes, pads and inserts are reviewed for product fit, handling and delivery requirements.", image: showcaseImages.foodBoxReal, href: "/packaging/takeout-boxes" },
  { number: "03", title: "Die-cut components", body: "Panels, inserts and support pieces move from structural review into sampling and finishing.", image: showcaseImages.machineClose, href: "/factory" },
  { number: "04", title: "Export-ready preparation", body: "Packing and project information are aligned for overseas B2B order coordination.", image: showcaseImages.machine, href: "/procurement" },
];

export default function HomeBusinessSections({ locale }: { locale: string }) {
  const isZh = locale === "zh";
  const visibleCategories = packagingCategories.slice(0, 8);
  return (
    <div className="kh-home-business-sections">
      <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8 lg:py-20">
        <div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-black uppercase tracking-[.22em] text-[#9a6b1f]">Featured product categories</p><h2 className="mt-3 text-4xl font-black tracking-[-.04em]">{isZh ? "从纸材到成品包装" : "From paper materials to finished packaging"}</h2></div><Link href="/packaging/all-products" className="inline-flex min-h-10 items-center gap-2 rounded-full border border-[#171713]/20 bg-white/75 px-4 text-sm font-black">{isZh ? "查看全部产品" : "View all products"}<ArrowRight className="size-4" /></Link></div>
        <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{visibleCategories.map((category) => <Link key={category.slug} href={`/packaging/${category.slug}`} className="group overflow-hidden rounded-lg border border-[#d9d2be] bg-white/75 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="relative h-36"><Image src={category.image} alt={`${category.title.en} packaging`} fill sizes="(min-width: 1024px) 25vw, 50vw" className="object-cover transition duration-300 group-hover:scale-[1.03]" /></div><div className="p-4"><h3 className="font-black">{isZh ? category.title.zh : category.title.en}</h3><p className="mt-2 line-clamp-2 text-sm leading-5 text-[#626156]">{isZh ? category.shortDescription.zh : category.shortDescription.en}</p><span className="mt-4 inline-flex items-center gap-2 text-xs font-black uppercase tracking-[.13em] text-[#805716]">Explore range <ArrowRight className="size-3.5" /></span></div></Link>)}</div>
      </section>

      <section className="border-y border-[#d9d2be] bg-white/55"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><div className="grid gap-5 lg:grid-cols-3"><ServiceCard title="Fast" body="Clear communication, quotation review, sampling and a predictable production handoff." /><ServiceCard title="Flexible" body="Size, structure, material, printing, surface treatment, inserts and order scope can be reviewed around the brief." /><ServiceCard title="Full-Service" body="From structural guidance and artwork support through sampling, production, inspection and repeat-order coordination." /></div></div></section>

      <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><div className="grid gap-8 lg:grid-cols-[.7fr_1.3fr] lg:items-start"><div><p className="text-xs font-black uppercase tracking-[.22em] text-[#9a6b1f]">Industries we serve</p><h2 className="mt-3 text-4xl font-black tracking-[-.04em]">{isZh ? "按应用选择包装路径" : "Choose a packaging path by application"}</h2><p className="mt-4 max-w-md text-base leading-7 text-[#626156]">{isZh ? "从应用出发，再用材料、结构和工艺收窄范围。" : "Start with the application, then narrow the range by material, structure and process."}</p><Link href="/industries" className="mt-6 inline-flex items-center gap-2 text-sm font-black text-[#805716]">Explore industries <ArrowRight className="size-4" /></Link></div><div className="grid gap-4 md:grid-cols-3">{industryGroups.map((group) => <Link key={group.slug} href="/industries" className="rounded-lg border border-[#d9d2be] bg-[#fbfaf5] p-5 shadow-sm transition hover:border-[#171713]/45"><h3 className="text-lg font-black">{group.title}</h3><p className="mt-3 text-sm leading-6 text-[#626156]">{group.description}</p><p className="mt-4 text-xs font-black uppercase tracking-[.13em] text-[#9a6b1f]">{group.applications.length} application paths</p></Link>)}</div></div></section>

      <section className="border-y border-[#d9d2be] bg-[#171713] text-white"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-black uppercase tracking-[.22em] text-[#e8c06c]">Four production lines</p><h2 className="mt-3 text-4xl font-black tracking-[-.04em]">{isZh ? "围绕规格协调生产" : "Production coordinated around the specification"}</h2></div><Link href="/factory" className="inline-flex min-h-10 items-center gap-2 rounded-full border border-white/20 px-4 text-sm font-black">Learn about our factory <ArrowRight className="size-4" /></Link></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{productionLines.map((line) => <Link key={line.number} href={line.href} className="group overflow-hidden rounded-lg border border-white/12 bg-white/6"><div className="relative h-40"><Image src={line.image} alt={line.title} fill sizes="(min-width: 1024px) 25vw, 50vw" className="object-cover opacity-90 transition duration-300 group-hover:scale-[1.03]" /></div><div className="p-4"><p className="text-xs font-black tracking-[.18em] text-[#e8c06c]">{line.number}</p><h3 className="mt-2 font-black">{line.title}</h3><p className="mt-2 text-sm leading-6 text-white/68">{line.body}</p></div></Link>)}</div></div></section>

      <section className="mx-auto grid max-w-7xl gap-6 px-4 py-14 sm:px-6 lg:grid-cols-[1.1fr_.9fr] lg:px-8 lg:py-20"><div className="rounded-lg border border-[#d9d2be] bg-white/75 p-7"><p className="text-xs font-black uppercase tracking-[.22em] text-[#9a6b1f]">About Foshan Kehong</p><h2 className="mt-3 text-3xl font-black tracking-[-.03em]">{isZh ? "纸材、结构和项目支持由同一团队协调" : "Paper materials, structures and project support coordinated by one team"}</h2><p className="mt-4 max-w-2xl text-base leading-7 text-[#626156]">{isZh ? "Kehong 是位于佛山的纸材加工与定制包装制造商，服务食品、烘焙、零售和电商项目。" : "Foshan Kehong is a paper converting and custom packaging manufacturer supporting food, bakery, retail and e-commerce projects."}</p><dl className="mt-6 grid gap-4 border-t border-[#d9d2be] pt-5 sm:grid-cols-3"><div><dt className="text-xs font-black uppercase tracking-[.13em] text-[#9a6b1f]">Location</dt><dd className="mt-1 text-sm font-bold">{companyProfile.location.en}</dd></div><div><dt className="text-xs font-black uppercase tracking-[.13em] text-[#9a6b1f]">Capability</dt><dd className="mt-1 text-sm font-bold">{companyProfile.productionCapability.en}</dd></div><div><dt className="text-xs font-black uppercase tracking-[.13em] text-[#9a6b1f]">Export</dt><dd className="mt-1 text-sm font-bold">{companyProfile.exportExperience.en}</dd></div></dl><div className="mt-7 flex flex-wrap gap-3"><Link href="/factory" className="inline-flex min-h-10 items-center gap-2 rounded-full bg-[#171713] px-4 text-sm font-black text-white">Learn about our factory <ArrowRight className="size-4" /></Link><Link href="/contact" className="inline-flex min-h-10 items-center rounded-full border border-[#171713]/20 px-4 text-sm font-black">Request a quote</Link></div></div><div className="rounded-lg border border-[#d9d2be] bg-[#fbfaf5] p-7"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-[#e8c06c]/25 text-[#9a6b1f]"><ShieldCheck className="size-5" /></span><h2 className="text-xl font-black">Quality Control & Third-Party Testing</h2></div><p className="mt-4 text-sm leading-6 text-[#626156]">Compliance documents are available upon request. Test scope, issuing body and date are confirmed against the relevant project records before sharing.</p><ul className="mt-5 grid gap-3 text-sm font-semibold text-[#4e4b42]"><li className="flex gap-2"><Check className="mt-1 size-4 text-[#9a6b1f]" />Specification and artwork review</li><li className="flex gap-2"><Check className="mt-1 size-4 text-[#9a6b1f]" />Sampling and structural checks</li><li className="flex gap-2"><Check className="mt-1 size-4 text-[#9a6b1f]" />Inspection before shipment</li></ul><Link href="/contact" className="mt-6 inline-flex items-center gap-2 text-sm font-black text-[#805716]">Ask for compliance documents <ArrowRight className="size-4" /></Link></div></section>

      <section className="mx-auto max-w-7xl px-4 pb-14 sm:px-6 lg:px-8 lg:pb-20"><div className="grid gap-4 rounded-lg border border-[#171713]/10 bg-[#e8c06c] p-7 sm:p-9 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#805716]">Start a packaging project</p><h2 className="mt-2 text-3xl font-black tracking-[-.03em]">{isZh ? "把需求交给我们，一起确认下一步" : "Bring your packaging brief into production."}</h2></div><Link href="/contact" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-full bg-[#171713] px-5 text-sm font-black text-white">Get a custom quote <ArrowRight className="size-4" /></Link></div></section>
    </div>
  );
}

function ServiceCard({ title, body }: { title: string; body: string }) {
  return <article className="rounded-lg border border-[#d9d2be] bg-[#fbfaf5] p-6"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-[#e8c06c]/25 text-[#9a6b1f]"><Layers3 className="size-4" /></span><h2 className="text-xl font-black">{title}</h2></div><p className="mt-4 text-sm leading-6 text-[#626156]">{body}</p></article>;
}
