import { ArrowRight, FileText, Palette, Ruler, Scissors } from "lucide-react";
import Header from "@/components/site/Header";
import SiteFooter from "@/components/site/SiteFooter";
import { Link } from "@/i18n/navigation";
import { finishOptions, resourceItems } from "@/data/siteContent";

const icons = [Palette, FileText, Scissors, Ruler, FileText, FileText];

export default function ResourcesPage({ locale }: { locale: string }) {
  const isZh = locale === "zh";
  return <div className="texture-paper min-h-screen bg-[#f6f4ec] text-[#171713]"><Header /><main>
    <section className="mx-auto max-w-7xl px-4 pb-12 pt-14 sm:px-6 lg:px-8 lg:pb-20 lg:pt-20"><p className="text-xs font-black uppercase tracking-[.24em] text-[#9a6b1f]">Kehong · Design Center</p><h1 className="mt-4 max-w-4xl text-5xl font-black leading-[.95] tracking-[-.05em] sm:text-7xl">{isZh ? "让文件、材料和结构更容易被确认" : "Resources for a cleaner packaging handoff."}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#626156]">{isZh ? "从 artwork、材料和工艺，到 dieline、选型和打样，先把采购问题整理清楚。" : "Use the Design Center to prepare artwork, compare materials and finishes, request a dieline and understand the sample path before production."}</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/contact" className="inline-flex min-h-11 items-center gap-2 rounded-full bg-[#171713] px-5 text-sm font-black text-white">Talk to a packaging expert <ArrowRight className="size-4" /></Link><Link href="/capabilities" className="inline-flex min-h-11 items-center rounded-full border border-[#171713]/18 bg-white/75 px-5 text-sm font-black">Explore capabilities</Link></div></section>
    <section className="border-y border-[#d9d2be] bg-white/60"><div className="mx-auto grid max-w-7xl gap-4 px-4 py-12 sm:px-6 md:grid-cols-2 lg:grid-cols-3 lg:px-8">{resourceItems.map((item, index) => { const Icon = icons[index] ?? FileText; return <article key={item.slug} className="rounded-lg border border-[#d9d2be] bg-[#fbfaf5] p-5"><div className="flex items-center justify-between gap-3"><span className="grid size-10 place-items-center rounded-full bg-[#e8c06c]/25 text-[#9a6b1f]"><Icon className="size-5" /></span><span className="text-[10px] font-black uppercase tracking-[.16em] text-[#9a6b1f]">{item.type === "request" ? "Request" : "Guide"}</span></div><h2 className="mt-4 text-xl font-black">{item.title}</h2><p className="mt-3 text-sm leading-6 text-[#626156]">{item.summary}</p><ul className="mt-4 grid gap-2">{item.topics.map((topic) => <li key={topic} className="flex gap-2 text-sm text-[#4e4b42]"><span className="mt-2 size-1.5 shrink-0 rounded-full bg-[#e8c06c]" />{topic}</li>)}</ul>{item.type === "request" ? <Link href="/contact" className="mt-5 inline-flex items-center gap-2 text-sm font-black text-[#805716]">Request a dieline <ArrowRight className="size-4" /></Link> : <span className="mt-5 inline-flex items-center gap-2 text-sm font-black text-[#805716]"><FileText className="size-4" />Read guide on this page</span>}</article>; })}</div></section>
    <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><div className="grid gap-6 lg:grid-cols-2"><div className="rounded-lg border border-[#d9d2be] bg-white/75 p-7"><h2 className="text-2xl font-black">Finishes at a glance</h2><div className="mt-5 grid gap-2 sm:grid-cols-2">{finishOptions.map((finish) => <p key={finish} className="rounded-md bg-[#fbfaf5] px-4 py-3 text-sm font-bold text-[#4e4b42]">{finish}</p>)}</div></div><div className="rounded-lg border border-[#171713]/10 bg-[#171713] p-7 text-white"><h2 className="text-2xl font-black">Need a structure recommendation?</h2><p className="mt-3 text-sm leading-6 text-white/70">Send the product, dimensions, quantity and destination. We will review the brief without forcing you to know every packaging term.</p><Link href="/contact" className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-full bg-[#e8c06c] px-5 text-sm font-black text-[#171713]">Start guided RFQ <ArrowRight className="size-4" /></Link></div></div></section>
  </main><SiteFooter /></div>;
}
