import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowRight } from "lucide-react";
import { setRequestLocale } from "next-intl/server";
import Header from "@/components/site/Header";
import SiteFooter from "@/components/site/SiteFooter";
import { Link } from "@/i18n/navigation";
import { getAlternateLanguages, getLocaleUrl, siteConfig } from "@/lib/site";
import { resourceItems } from "@/data/siteContent";

export function generateStaticParams() { return ["en", "zh", "es", "th", "vi", "id", "ms"].flatMap((locale) => resourceItems.map((item) => ({ locale, slug: item.slug }))); }
export async function generateMetadata({ params }: { params: Promise<{ locale: string; slug: string }> }): Promise<Metadata> { const { locale, slug } = await params; const item = resourceItems.find((resource) => resource.slug === slug); if (!item) return {}; const canonical = await getLocaleUrl(locale, `/resources/${slug}`); return { metadataBase: new URL(siteConfig.url), title: `${item.title} | Kehong`, description: item.summary, alternates: { canonical, languages: await getAlternateLanguages(`/resources/${slug}`) }, openGraph: { title: `${item.title} | Kehong`, description: item.summary, url: canonical, siteName: siteConfig.name, type: "article" } }; }
export default async function ResourceDetailPage({ params }: { params: Promise<{ locale: string; slug: string }> }) { const { locale, slug } = await params; const item = resourceItems.find((resource) => resource.slug === slug); if (!item) notFound(); setRequestLocale(locale); return <div className="texture-paper min-h-screen bg-[#f6f4ec] text-[#171713]"><Header /><main className="mx-auto max-w-4xl px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><Link href="/resources" className="inline-flex items-center gap-2 text-sm font-black text-[#805716]"><ArrowLeft className="size-4" />Resources & Design Center</Link><p className="mt-10 text-xs font-black uppercase tracking-[.22em] text-[#9a6b1f]">Kehong · {item.type === "request" ? "Request" : "Guide"}</p><h1 className="mt-3 text-5xl font-black leading-[.95] tracking-[-.05em]">{item.title}</h1><p className="mt-6 text-lg leading-8 text-[#626156]">{item.summary}</p><section className="mt-10 rounded-lg border border-[#d9d2be] bg-white/80 p-6 sm:p-8"><h2 className="text-2xl font-black">What to prepare</h2><ul className="mt-5 grid gap-3">{item.topics.map((topic) => <li key={topic} className="flex gap-3 text-sm leading-6 text-[#4e4b42]"><span className="mt-2 size-2 shrink-0 rounded-full bg-[#e8c06c]" />{topic}</li>)}</ul><p className="mt-6 border-t border-[#d9d2be] pt-5 text-sm leading-6 text-[#626156]">Kehong confirms project-specific technical parameters against the approved brief. No public download is shown until a verified company file is available.</p></section><Link href={item.type === "request" ? "/contact" : "/contact"} className="mt-8 inline-flex min-h-11 items-center gap-2 rounded-full bg-[#171713] px-5 text-sm font-black text-white">{item.type === "request" ? "Request a dieline" : "Discuss this with a packaging expert"}<ArrowRight className="size-4" /></Link></main><SiteFooter /></div>; }
